version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    volumes:
      - ${APPs:-./apps}:/opt/splunk/etc/apps
      - ${DEFAULT_YML:-./default.yml}:/tmp/default.yml
      - ${MY_DATA:-./data}:/tmp/data
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-splunk123}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN:-abcd1234}
    ports:
      - 8000:8000
      - 8089:8089
      - 8088:8088
      - 1514:1514
      - 9997:9997

volumes:
  apps: